-- Дополнительные поля аккаунта, личный кабинет и коды подтверждения.

ALTER TABLE "Users"
ADD COLUMN IF NOT EXISTS "Email" varchar(120),
ADD COLUMN IF NOT EXISTS "PhoneNumber" varchar(30),
ADD COLUMN IF NOT EXISTS "EmailConfirmed" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "PhoneNumberConfirmed" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "ProfilePhotoPath" varchar(300);

UPDATE "Users"
SET "Email" = CASE
        WHEN "UserName" = 'admin' THEN 'admin@example.edu'
        WHEN "UserName" = 'teacher' THEN 'sidorov@example.edu'
        WHEN "UserName" = 'student' THEN 'student@example.edu'
        ELSE "Email"
    END,
    "PhoneNumber" = CASE
        WHEN "UserName" = 'admin' THEN '+375291111111'
        WHEN "UserName" = 'teacher' THEN '+375292222222'
        WHEN "UserName" = 'student' THEN '+375293333333'
        ELSE "PhoneNumber"
    END
WHERE "Email" IS NULL OR "PhoneNumber" IS NULL;

UPDATE "Users"
SET "EmailConfirmed" = true,
    "PhoneNumberConfirmed" = true
WHERE "UserName" = 'admin';

UPDATE "Users"
SET "EmailConfirmed" = true
WHERE "UserName" = 'teacher';

CREATE TABLE IF NOT EXISTS "VerificationCodes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Purpose" varchar(40) NOT NULL,
    "Destination" varchar(120) NOT NULL,
    "Code" varchar(6) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    "ResetToken" varchar(80)
);

CREATE INDEX IF NOT EXISTS "IX_VerificationCodes_UserId_Purpose_Code"
ON "VerificationCodes"("UserId", "Purpose", "Code");
