-- Заявки студентов на справки и ведомости пересдачи.
-- Скрипт можно выполнить вручную, если нужно создать таблицу без запуска приложения.

CREATE TABLE IF NOT EXISTS "StatementRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" integer NOT NULL REFERENCES "Students"("Id") ON DELETE CASCADE,
    "RequestType" varchar(40) NOT NULL,
    "Status" varchar(40) NOT NULL,
    "CertificateWithEmblem" boolean NOT NULL DEFAULT false,
    "CertificatePurpose" varchar(80),
    "SubjectId" integer REFERENCES "Subjects"("Id") ON DELETE SET NULL,
    "TeacherId" integer REFERENCES "Teachers"("Id") ON DELETE SET NULL,
    "MissedDate" timestamp without time zone,
    "AbsenceReason" varchar(40),
    "AdminComment" varchar(500),
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PrintedAt" timestamp without time zone
);
